

# Executive Summary {-}

The health and viability of freshwater fish populations can depend on access to tributary and off channel areas which provide refuge during high flows, opportunities for foraging, overwintering habitat, spawning habitat and summer rearing habitat. As road crossing structures are commonly upgraded or removed there are numerous opportunities to restore connectivity by ensuring that fish passage considerations are incorporated into repair, replacement, relocation and deactivation designs. 

<br>

The Society for Ecosystem Restoration in Northern BC (SERNbc) is working together with the McLeod Lake Indian Band, the Peace Region Fish and Wildlife Compensation Program (FWCP), the Provincial Fish Passage Technical Working Group (FPTWG), road/rail tenure holders and other FWCP stakeholders/partners to prioritize, plan and fund the restoration of fish passage at Parsnip River watershed road crossing structure barriers. 

<br>

The project engages FWCP partners and stakeholders to clearly communicate fish passage issues in the Parsnip River watershed while collaboratively planning and executing the steps necessary to realize fish passage restorations. Work completed and ongoing aligns with the Fish and Wildlife Compensation Program Rivers, Lakes and Reservoirs Action Plan [@fishandwildlifecompensationprogram2020PeaceRegion] sub objective 6 of addressing fish passage issues in streams to enhance productivity of priority species.  Project activities undertaken fullfill with the following actions:

  * PEA.RLR.S06.RI.20 - Conducting engagement to prioritize options for fish passage improvement-P1 
  * PEA.RLR.S06.RI.19 - Conducting research to prioritize fish passage actions-P1
  * PEA.RLR.S06.HB.21 - Restoring fish access to streams-P1
  
<br>


This project builds on Society for Ecosystem Restoration Northern BC (SERNbc) work in 2019 - 2020 and 2021 - 2022 which can be referenced [here](https://newgraphenvironment.github.io/Parsnip_Fish_Passage/) [@irvine2020ParsnipRiver] and [here](https://newgraphenvironment.github.io/fish_passage_parsnip_2021_reporting/) [@irvine2022PEAF22F3577DCARestoring]. In 2019/2020, following a literature review, analysis of fish habitat modelling data, the Provincial Stream Crossing Inventory System (PSCIS) and a community scoping exercise within the McLeod Lake Indian Band habitat confirmation assessments were conducted at 17 sites throughout the Parsnip River watershed with 10 crossings rated as high priorities for rehabilitation and three crossings rated as moderate priorities for restoration. In 2021/2022, project activities continued with funding raised by SERNbc to initiate restoration activities of a high priority crossing in the Missinka River watershed.  Additionally, partner engagement, planning, field assessments and reporting lined up assessments for restoration opportunities, built capacity for ecosystem restoration and provided the data necessary to implement and monitor restoration actions. 


<br>

In 2021/2022, through support from FWCP for this project, and leveraging numerous other connectivity restoration initiatives underway throughout the province, we were able to source funding and in-kind efforts from the Ministry of Forests, Lands and Natural Resource Operations and Rural Development, the Fish Passage Technical Working Group and forest road tenure holders to catalyze fish passage restoration actions in the Parsnip River watershed group. 

<br>

In 2022/2023, through this collaborative project, and leveraging numerous other connectivity restoration initiatives underway throughout the province, we engaged numerous project partners and were able to catalyze fish passage restoration activities at multiple sites identified as high priorities in 2019/2020 and 2021/2022. Additionally, McLeod Lake crews were trained, multiple sites were assessed in the field including fish sampling work near Arctic Lake, PSCIS crossing 125179 - Tributary to Missinka River was replaced, two crossings on the Chuchinka-Table FSR were prioritized for replacement in 2024 - 2025 with engineering designs commissioned and materials purchased. 

<br>

In 2021/2022 actions were initiated to facilitate replacement of high priority PSCIS crossing 125179 on the Chuchinka-Missinka FSR with a clearspan bridge in the summer of 2022. The bridge structure and associated materials were purchased and environmental permitting/management planning has been initiated. Through financial support from FWCP and the Fish Passage Technical Working Group, as well as in-kind and monetary support from Sinclar Group Forest Products, remediation of fish passage at this site will be completed in 2022.  

<br>

Engineering design, project permitting, environmental management planning as well as the purchase/mobilization of the bridge structure, abutment riprap and materials is planned for 2022/2023 at high priority PSCIS crossing 125000 on the Chuchinka-Arctic FSR.  Installation of the clearspan structure has been scheduled for 2023. 

<br>

British Columbia Timber Sales is planning to deactivate the Chuchinka-Colbourne FSR between the location of high priority crossing PSCIS 125345 on a tributary to the Parsnip River and the Chuchinka-Anzac FSR. The work is schedule for July and August of 2022. 

<br>

Through the ongoing development of open source analysis and data presentation tools we are identifying and communicating connectivity issues while planning on the ground works to assess opportunities, build capacity and provide the data necessary to implement and monitor restoration actions.  Planning, field assessments and follow up reporting will continue to include engagement with road/rail/forest tenure holders, build awareness for connectivity issues in the wider community and build capacity for ecosystem restoration in the Peace Region. 


<br>

We are leveraging this project together with numerous others to contributing to the open source development of database building, habitat/connectivity modeling and data presentation tools to conduct reproducible analysis/presentation of fish passage restoration opportunities in the Peace Region.  This work facilitates outreach, prioritizes sites and provides the background information necessary to communicate restoration plans/actions effectively. 


<br>

Field surveys planned for 2022 and beyond will contribute to McLeod Lake Indian Band capacity building programs, helping facilitate indigenous partnerships in natural resource management and stewardship within traditional territories. On the ground research and monitoring is an essential part of any restoration program and is necessary to ensure the best and most efficient opportunities for fish passage restoration are realized while incorporating adaptive management informed by traditional knowledge and defensible planning/monitoring data.

<br>

Updated maps for the Parsnip River, Carp River and Crooked River watershed groups incorporating the newly developed sa'ba (bull trout) spawning and rearing habitat model have been produced and are available [here](https://hillcrestgeo.ca/outgoing/fishpassage/projects/parsnip/archive/2022-05-27/). 

<br>

An online connectivity mapping portal for the Peace Region has been launched and is located [here](https://newgraphenvironment.github.io/fish_passage_parsnip_2021_webmap). At the time of reporting the site was undergoing development with the interface expected to evolve significantly over the coming months.   

<br>

Although remediation and replacement of stream crossing structures can have significant benefits to local fish populations, the costs of remedial works can be significant and the impacts of the work often complex to evaluate and quantify. Additionally, allocation of ecosystem restoration funding towards infrastructure upgrades on transportation right of ways are not always considered ethical under all circumstances from all perspectives. When funds are finite and invested groups are engaged in fund raising, cost benefits and the ethics of crossing replacements should be explored collaboratively alongside the cost benefits and ethics of alternative/complimentary investments including transportation corridor relocation/deactivation, land procurement/covenant, cattle exclusion, riparian/floodplain restoration, habitat complexing, water conservation, commercial/recreational fishing management and research.
