# Recommendations

 - Continue to engage partners to raise funds for remediations, identify sites for restoration, conduct remedial works and assess effectiveness of works.
 - Expand study area to include the Carp Lake and Crooked River watershed groups to provide more options for remediation and engage additional partners (ex. Ministry of Transportation and Infrastructure).
 - Conduct baseline monitoring at sites where sites have been prioritized and where remediations are planned. Electrofishing surveys are recommended along with tagging of target species with PIT tags to track health and movement over time. 
 - Conduct follow up monitoring at site 125179 in the Missinka where the bridge was installed in 2022. Electrofishing with tagging of target species is recommended along with photo documentation of stream morphology near the bridge. Fish sampling in the adjacent similar sized stream [(PSCIS crossing 125180)](https://www.newgraphenvironment.com/Parsnip_Fish_Passage/03_Parsnip_report_125180.html) containing culverts ranked as barriers can provide reference site data for comparison.
